In [1]:
import requests
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

# r = requests.get("https://opendata.epa.gov.tw/ws/Data/AQI/?$format=json", verify=False)
# print(r.status_code)

/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.8) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "

In [ ]:
# type(r)

In [ ]:
# type(r.json())

In [ ]:
# lst = r.json()
# lst[0]

In [ ]:
# for i in lst[:3]:
#     print(i["County"], i["SiteName"], i["PM2.5"])

In [ ]:
# dimen = np.array(lst).shape
# dimen

### 局屬氣象站資料(現在天氣觀測報告)-本局局屬有人氣象站資料

In [2]:
r2 = requests.get("https://opendata.cwb.gov.tw/api/v1/rest/datastore/O-A0003-001?Authorization=CWB-A0B581C8-BDD4-4809-A61D-DD7FB8DD8105", verify=False)
lst2 = r2.json()
station_num = len(lst2["records"]["location"])
for i in range(2):
    if lst2["records"]["location"][i]["locationName"][0]!="國":
        print(#'{:6}'.format(lst2["records"]["location"][i]["locationName"])+
             '地點:'+lst2["records"]["location"][i]["locationName"]+'('+lst2["records"]["location"][i]["parameter"][0]["parameterValue"]+lst2["records"]["location"][i]["parameter"][2]["parameterValue"]+'),'+
             # lst2["records"]["location"][i]["lat"]+','+
             # lst2["records"]["location"][i]["lon"]+','+
             lst2["records"]["location"][i]["time"]["obsTime"][:13]+','+
             '高度:'+lst2["records"]["location"][i]["weatherElement"][0]["elementValue"]+','+ #ELEV
             '風向:'+lst2["records"]["location"][i]["weatherElement"][1]["elementValue"]+','+ #WDIR
             '風速:'+lst2["records"]["location"][i]["weatherElement"][2]["elementValue"]+','+ #WDSD
             '溫度:'+lst2["records"]["location"][i]["weatherElement"][3]["elementValue"]+','+ #TEMP
             '相對濕度:'+lst2["records"]["location"][i]["weatherElement"][4]["elementValue"]+','+ #HUMD
             '測站氣壓:'+lst2["records"]["location"][i]["weatherElement"][5]["elementValue"]+','+ #PRES
             '日累積雨量:'+lst2["records"]["location"][i]["weatherElement"][6]["elementValue"]+','+ #24R
             # 'H_FX小時最大陣風風速:'+lst2["records"]["location"][i]["weatherElement"][7]["elementValue"]+','+
             # 'H_XD小時最大陣風風向:'+'{:8}'.format(lst2["records"]["location"][i]["weatherElement"][8]["elementValue"])+
             # 'H_FXT小時最大陣風時間:'+'{:8}'.format(lst2["records"]["location"][i]["weatherElement"][9]["elementValue"])+
             # 'H_F10:'+'{:8}'.format(lst2["records"]["location"][i]["weatherElement"][10]["elementValue"])+
             # 'H_10D:'+'{:8}'.format(lst2["records"]["location"][i]["weatherElement"][11]["elementValue"])+
             # 'H_F10T:'+'{:8}'.format(lst2["records"]["location"][i]["weatherElement"][12]["elementValue"])+
             # 'H_UVI:'+'{:8}'.format(lst2["records"]["location"][i]["weatherElement"][13]["elementValue"])+
             'D_TX最高溫:'+lst2["records"]["location"][i]["weatherElement"][14]["elementValue"]+','+
             # 'D_TXT本日最高溫發生時間:'+'{:8}'.format(lst2["records"]["location"][i]["weatherElement"][15]["elementValue"])+
             'D_TN最低溫:'+lst2["records"]["location"][i]["weatherElement"][16]["elementValue"]+','+
             # 'D_TNT本日最低溫發生時間:'+'{:8}'.format(lst2["records"]["location"][i]["weatherElement"][17]["elementValue"])+
             # 'D_TS:'+'{:8}'.format(lst2["records"]["location"][i]["weatherElement"][18]["elementValue"])+
             # 'VIS:'+'{:8}'.format(lst2["records"]["location"][i]["weatherElement"][19]["elementValue"])+
             'Weather:'+lst2["records"]["location"][i]["weatherElement"][20]["elementValue"]
             )

地點:南沙島(高雄市旗津區),2022-01-13 14,高度:4.50,風向:-99,風速:-99,溫度:-99,相對濕度:-99,測站氣壓:-99,日累積雨量:-99,D_TX最高溫:-99,D_TN最低溫:-99,Weather:-99

In [3]:
dict1,dict2,dict3,dict4,dict5,dict6,dict7,dict8,dict9,dict10,dict11,dict12,dict13,dict14,dict15={},{},{},{},{},{},{},{},{},{},{},{},{},{},{}
for i in range(station_num):
    if lst2["records"]["location"][i]["locationName"][0]!="國":
        dict1.setdefault(lst2["records"]["location"][i]["locationName"],lst2["records"]["location"][i]["time"]["obsTime"][:13])
        # dict2.setdefault(lst2["records"]["location"][i]["locationName"],lst2["records"]["location"][i]["weatherElement"][0]["elementValue"])        
        # dict3.setdefault(lst2["records"]["location"][i]["locationName"],lst2["records"]["location"][i]["weatherElement"][1]["elementValue"])
        dict4.setdefault(lst2["records"]["location"][i]["locationName"],lst2["records"]["location"][i]["weatherElement"][2]["elementValue"])
        dict5.setdefault(lst2["records"]["location"][i]["locationName"],lst2["records"]["location"][i]["weatherElement"][3]["elementValue"])
        dict6.setdefault(lst2["records"]["location"][i]["locationName"],lst2["records"]["location"][i]["weatherElement"][4]["elementValue"])
        dict7.setdefault(lst2["records"]["location"][i]["locationName"],lst2["records"]["location"][i]["weatherElement"][5]["elementValue"])
        dict8.setdefault(lst2["records"]["location"][i]["locationName"],lst2["records"]["location"][i]["weatherElement"][6]["elementValue"])
        dict9.setdefault(lst2["records"]["location"][i]["locationName"],lst2["records"]["location"][i]["weatherElement"][14]["elementValue"])
        dict10.setdefault(lst2["records"]["location"][i]["locationName"],lst2["records"]["location"][i]["weatherElement"][16]["elementValue"])
        dict11.setdefault(lst2["records"]["location"][i]["locationName"],lst2["records"]["location"][i]["weatherElement"][20]["elementValue"])
        dict12.setdefault(lst2["records"]["location"][i]["locationName"],lst2["records"]["location"][i]["parameter"][0]["parameterValue"]+lst2["records"]["location"][i]["parameter"][2]["parameterValue"])
        dict13.setdefault(lst2["records"]["location"][i]["locationName"],lst2["records"]["location"][i]["lat"])
        dict14.setdefault(lst2["records"]["location"][i]["locationName"],lst2["records"]["location"][i]["lon"])
        dict15.setdefault(lst2["records"]["location"][i]["locationName"],lst2["records"]["location"][i]["locationName"])

In [4]:
for i in range(1,16):
    locals()['s'+str(i)] = pd.Series(locals()['dict'+str(i)])

In [5]:
df = pd.DataFrame({'日期': s1,'風速': s4,'溫度': s5,'相對濕度': s6,'測站氣壓': s7,
                    '日累積雨量': s8,'最高溫': s9,'最低溫': s10,'Weather': s11,'縣市': s12,'lat': s13,'lon': s14,'地點': s15})

In [ ]:
# df

In [6]:
df.loc["嘉義"] # 用index標籤取值

日期         2022-01-13 14
風速                  4.70
溫度                 20.30
相對濕度                0.57
測站氣壓             1014.40
日累積雨量                  0
最高溫                22.50
最低溫                10.60
Weather                晴
縣市                 嘉義市西區
lat            23.497671
lon           120.424783
地點                    嘉義
Name: 嘉義, dtype: object

In [7]:
df.iloc[10] # 用index位置取資料

日期         2022-01-13 14
風速                  5.80
溫度                  2.90
相對濕度                0.77
測站氣壓                 -99
日累積雨量                  0
最高溫                 7.60
最低溫                -2.70
Weather               多雲
縣市                花蓮縣秀林鄉
lat            24.146253
lon           121.268245
地點                   合歡山
Name: 合歡山, dtype: object

In [8]:
r3 = requests.get("https://opendata.cwb.gov.tw/api/v1/rest/datastore/O-A0001-001?Authorization=CWB-A0B581C8-BDD4-4809-A61D-DD7FB8DD8105", verify=False)
lst3 = r3.json()
station_num2 = len(lst3["records"]["location"])

In [9]:
for i in range(3):
    if lst3["records"]["location"][i]["locationName"][0]!="國":
        print(#'{:6}'.format(lst2["records"]["location"][i]["locationName"])+
             '地點:'+lst3["records"]["location"][i]["locationName"]+'('+lst3["records"]["location"][i]["parameter"][0]["parameterValue"]+lst3["records"]["location"][i]["parameter"][2]["parameterValue"]+'),'+
             # lst2["records"]["location"][i]["lat"]+','+
             # lst2["records"]["location"][i]["lon"]+','+
             lst3["records"]["location"][i]["time"]["obsTime"][:13]+','+
             '高度:'+lst3["records"]["location"][i]["weatherElement"][0]["elementValue"]+','+ #ELEV
             '風向:'+lst3["records"]["location"][i]["weatherElement"][1]["elementValue"]+','+ #WDIR
             '風速:'+lst3["records"]["location"][i]["weatherElement"][2]["elementValue"]+','+ #WDSD
             '溫度:'+lst3["records"]["location"][i]["weatherElement"][3]["elementValue"]+','+ #TEMP
             '相對濕度:'+lst3["records"]["location"][i]["weatherElement"][4]["elementValue"]+','+ #HUMD
             '測站氣壓:'+lst3["records"]["location"][i]["weatherElement"][5]["elementValue"]+','+ #PRES
             '日累積雨量:'+lst3["records"]["location"][i]["weatherElement"][6]["elementValue"]+','+ #24R
             # 'H_FX小時最大陣風風速:'+lst2["records"]["location"][i]["weatherElement"][7]["elementValue"]+','+
             # 'H_XD小時最大陣風風向:'+'{:8}'.format(lst2["records"]["location"][i]["weatherElement"][8]["elementValue"])+
             # 'H_FXT小時最大陣風時間:'+'{:8}'.format(lst2["records"]["location"][i]["weatherElement"][9]["elementValue"])+
             'D_TX最高溫:'+lst3["records"]["location"][i]["weatherElement"][10]["elementValue"]+','+
             # 'D_TXT本日最高溫發生時間:'+'{:8}'.format(lst2["records"]["location"][i]["weatherElement"][15]["elementValue"])+
             'D_TN最低溫:'+lst3["records"]["location"][i]["weatherElement"][12]["elementValue"]
             # 'D_TNT本日最低溫發生時間:'+'{:8}'.format(lst2["records"]["location"][i]["weatherElement"][17]["elementValue"])+
             )

地點:福山(新北市烏來區),2022-01-13 14,高度:405.0,風向:-99,風速:-99,溫度:-99,相對濕度:-99,測站氣壓:-99,日累積雨量:-99,D_TX最高溫:-99,D_TN最低溫:-99
地點:安平(臺南市安平區),2022-01-13 14,高度:10.0,風向:343,風速:3.7,溫度:19.7,相對濕度:0.68,測站氣壓:1016.3,日累積雨量:0.0,D_TX最高溫:21.50,D_TN最低溫:13.80
地點:七塊厝(臺東縣東河鄉),2022-01-13 14,高度:415.0,風向:67,風速:2.0,溫度:17.3,相對濕度:0.84,測站氣壓:969.7,日累積雨量:0.0,D_TX最高溫:18.90,D_TN最低溫:12.40

In [10]:
dictt1,dictt2,dictt3,dictt4,dictt5,dictt6,dictt7,dictt8,dictt9,dictt10,dictt11,dictt12,dictt13,dictt14,dictt15={},{},{},{},{},{},{},{},{},{},{},{},{},{},{}
for i in range(station_num2):
    if lst3["records"]["location"][i]["locationName"][0]!="國":
        dictt1.setdefault(lst3["records"]["location"][i]["locationName"],lst3["records"]["location"][i]["time"]["obsTime"][:13])
        # dictt2.setdefault(lst3["records"]["location"][i]["locationName"],lst3["records"]["location"][i]["weatherElement"][0]["elementValue"])        
        # dictt3.setdefault(lst3["records"]["location"][i]["locationName"],lst3["records"]["location"][i]["weatherElement"][1]["elementValue"])
        dictt4.setdefault(lst3["records"]["location"][i]["locationName"],lst3["records"]["location"][i]["weatherElement"][2]["elementValue"])
        dictt5.setdefault(lst3["records"]["location"][i]["locationName"],lst3["records"]["location"][i]["weatherElement"][3]["elementValue"])
        dictt6.setdefault(lst3["records"]["location"][i]["locationName"],lst3["records"]["location"][i]["weatherElement"][4]["elementValue"])
        dictt7.setdefault(lst3["records"]["location"][i]["locationName"],lst3["records"]["location"][i]["weatherElement"][5]["elementValue"])
        dictt8.setdefault(lst3["records"]["location"][i]["locationName"],lst3["records"]["location"][i]["weatherElement"][6]["elementValue"])
        dictt9.setdefault(lst3["records"]["location"][i]["locationName"],lst3["records"]["location"][i]["weatherElement"][10]["elementValue"])
        dictt10.setdefault(lst3["records"]["location"][i]["locationName"],lst3["records"]["location"][i]["weatherElement"][12]["elementValue"])
        dictt11.setdefault('Weather','')
        dictt12.setdefault(lst3["records"]["location"][i]["locationName"],lst3["records"]["location"][i]["parameter"][0]["parameterValue"]+lst3["records"]["location"][i]["parameter"][2]["parameterValue"])
        dictt13.setdefault(lst3["records"]["location"][i]["locationName"],lst3["records"]["location"][i]["lat"])
        dictt14.setdefault(lst3["records"]["location"][i]["locationName"],lst3["records"]["location"][i]["lon"])
        dictt15.setdefault(lst3["records"]["location"][i]["locationName"],lst3["records"]["location"][i]["locationName"])

In [11]:
for i in range(1,16):
    locals()['ss'+str(i)] = pd.Series(locals()['dictt'+str(i)])

df2 = pd.DataFrame({'日期': ss1,'風速': ss4,'溫度': ss5,'相對濕度': ss6,'測站氣壓': ss7,
                    '日累積雨量': ss8,'最高溫': ss9,'最低溫': ss10,'Weather': ss11,'縣市': ss12,'lat': ss13,'lon': ss14,'地點': ss15})

In [12]:
df2

,日期,風速,溫度,相對濕度,測站氣壓,日累積雨量,最高溫,最低溫,Weather,縣市,lat,lon,地點
Weather,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN,NaN
七塊厝,2022-01-13 14,2.0,17.3,0.84,969.7,0.0,18.90,12.40,NaN,臺東縣東河鄉,22.956258,121.221844,七塊厝
七股,2022-01-13 14,11.9,18.5,0.69,1018.2,0.0,19.20,14.30,NaN,臺南市七股區,23.149036,120.078164,七股
三和,2022-01-13 14,1.5,11.2,0.73,996.0,2.5,12.40,11.20,NaN,新北市金山區,25.234933,121.586997,三和
三地門,2022-01-13 14,2.0,26.0,0.27,1003.2,0.0,26.80,11.90,NaN,屏東縣內埔鄉,22.711667,120.631889,三地門
...,...,...,...,...,...,...,...,...,...,...,...,...,...
龍井,2022-01-13 14,5.8,17.3,0.6,1018.9,0.0,18.00,13.00,NaN,臺中市龍井區,24.186278,120.520833,龍井
龍潭,2022-01-13 14,2.4,12.1,0.7,993.1,-99,12.70,12.10,NaN,桃園市龍潭區,24.871833,121.213194,龍潭
龍磐,2022-01-13 14,4.4,21.0,0.72,1004.2,0.0,22.20,15.20,NaN,屏東縣恆春鎮,21.933481,120.830933,龍磐
龜山,2022-01-13 14,3.7,11.8,0.7,992.9,-99,12.70,11.80,NaN,桃園市龜山區,25.030231,121.378336,龜山
龜山島,2022-01-13 14,-99,11.3,0.8,972.6,0.0,12.80,11.30,NaN,宜蘭縣頭城鎮,24.843392,121.944947,龜山島

In [13]:
df_all = pd.concat([df,df2]) # 合併

In [14]:
df_all.sort_values(by=['縣市'],ascending=False)

,日期,風速,溫度,相對濕度,測站氣壓,日累積雨量,最高溫,最低溫,Weather,縣市,lat,lon,地點
鼓山,2022-01-13 14,4.6,22.7,0.56,1014.0,-99,23.60,14.70,NaN,高雄市鼓山區,22.625139,120.267500,鼓山
鳳山,2022-01-13 14,1.6,25.0,0.45,1013.6,-99,25.10,14.20,NaN,高雄市鳳山區,22.648611,120.348056,鳳山
阿蓮,2022-01-13 14,3.0,23.1,0.44,1012.5,0.0,23.10,12.80,NaN,高雄市阿蓮區,22.884944,120.319528,阿蓮
路竹,2022-01-13 14,4.4,23.5,0.44,1011.9,-99,23.60,14.80,NaN,高雄市路竹區,22.856639,120.251361,路竹
茄萣,2022-01-13 14,3.2,19.9,0.68,1015.6,0.0,21.80,14.10,NaN,高雄市茄萣區,22.908444,120.174583,茄萣
...,...,...,...,...,...,...,...,...,...,...,...,...,...
小奇萊,2022-01-13 14,6.0,1.0,1,699.1,1.0,2.00,-2.50,NaN,南投縣仁愛鄉,24.133550,121.287556,小奇萊
奇萊稜線A,2022-01-13 14,12.1,-0.6,1,-99,0.0,-0.20,-3.70,NaN,南投縣仁愛鄉,24.111019,121.318297,奇萊稜線A
仁愛,2022-01-13 14,1.2,15.7,0.57,888.0,0.0,15.80,8.50,NaN,南投縣仁愛鄉,24.023903,121.124056,仁愛
中寮,2022-01-13 14,1.3,21.1,0.48,995.5,-99,21.10,10.40,NaN,南投縣中寮鄉,23.886278,120.758528,中寮
Weather,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN,NaN

In [15]:
df_all.index #看看有哪些index

Index(['南沙島', '嘉義', '大安森林', '臺北', '新屋', '梧棲', '高雄', '臺中', '新竹', '淡水',
       ...
       '鹿野', '麟洛', '麻豆', '鼓山', '鼻頭角', '龍井', '龍潭', '龍磐', '龜山', '龜山島'],
      dtype='object', length=460)

In [16]:
df_all.loc["小奇萊"]

日期         2022-01-13 14
風速                   6.0
溫度                   1.0
相對濕度                   1
測站氣壓               699.1
日累積雨量                1.0
最高溫                 2.00
最低溫                -2.50
Weather              NaN
縣市                南投縣仁愛鄉
lat            24.133550
lon           121.287556
地點                   小奇萊
Name: 小奇萊, dtype: object

In [17]:
df_all.iloc[250]

日期         2022-01-13 14
風速                   3.1
溫度                  20.9
相對濕度                0.55
測站氣壓              1006.6
日累積雨量                0.0
最高溫                21.00
最低溫                10.60
Weather              NaN
縣市                雲林縣林內鄉
lat            23.750436
lon           120.601508
地點                    林內
Name: 林內, dtype: object

In [18]:
for i in range(df_all.shape[0]): # df的列數
    for j in range(13):
        if pd.isna(df_all.iloc[i][j]):
            df_all.iloc[i][j]=''

In [19]:
pd.isna(df_all)

,日期,風速,溫度,相對濕度,測站氣壓,日累積雨量,最高溫,最低溫,Weather,縣市,lat,lon,地點
南沙島,False,False,False,False,False,False,False,False,False,False,False,False,False
嘉義,False,False,False,False,False,False,False,False,False,False,False,False,False
大安森林,False,False,False,False,False,False,False,False,False,False,False,False,False
臺北,False,False,False,False,False,False,False,False,False,False,False,False,False
新屋,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
龍井,False,False,False,False,False,False,False,False,False,False,False,False,False
龍潭,False,False,False,False,False,False,False,False,False,False,False,False,False
龍磐,False,False,False,False,False,False,False,False,False,False,False,False,False
龜山,False,False,False,False,False,False,False,False,False,False,False,False,False
龜山島,False,False,False,False,False,False,False,False,False,False,False,False,False

In [22]:
df_all

,日期,風速,溫度,相對濕度,測站氣壓,日累積雨量,最高溫,最低溫,Weather,縣市,lat,lon,地點
南沙島,2022-01-13 14,-99,-99,-99,-99,-99,-99,-99,-99,高雄市旗津區,10.371770,114.356682,南沙島
嘉義,2022-01-13 14,4.70,20.30,0.57,1014.40,0,22.50,10.60,晴,嘉義市西區,23.497671,120.424783,嘉義
大安森林,2022-01-13 14,0.50,13.80,0.64,-99,0,14.80,12.60,陰,臺北市大安區,25.031331,121.528056,大安森林
臺北,2022-01-13 14,1.10,14.20,0.64,1018.50,0.50,15.40,13.30,陰,臺北市中正區,25.039410,121.506676,臺北
新屋,2022-01-13 14,7.90,13.90,0.63,1019.50,0,15.40,12.30,陰,桃園市新屋區,25.008503,121.039267,新屋
...,...,...,...,...,...,...,...,...,...,...,...,...,...
龍井,2022-01-13 14,5.8,17.3,0.6,1018.9,0.0,18.00,13.00,,臺中市龍井區,24.186278,120.520833,龍井
龍潭,2022-01-13 14,2.4,12.1,0.7,993.1,-99,12.70,12.10,,桃園市龍潭區,24.871833,121.213194,龍潭
龍磐,2022-01-13 14,4.4,21.0,0.72,1004.2,0.0,22.20,15.20,,屏東縣恆春鎮,21.933481,120.830933,龍磐
龜山,2022-01-13 14,3.7,11.8,0.7,992.9,-99,12.70,11.80,,桃園市龜山區,25.030231,121.378336,龜山
龜山島,2022-01-13 14,-99,11.3,0.8,972.6,0.0,12.80,11.30,,宜蘭縣頭城鎮,24.843392,121.944947,龜山島

In [20]:
lst_sql = df_all.values.tolist()

In [21]:
lst_sql[0]

['2022-01-13 14',
 '-99',
 '-99',
 '-99',
 '-99',
 '-99',
 '-99',
 '-99',
 '-99',
 '高雄市旗津區',
 '10.371770',
 '114.356682',
 '南沙島']

In [ ]:
# for i in range(len(lst_sql)):
#     print(lst_sql[i])

In [ ]:
import pyodbc

In [ ]:
len(lst_sql)

In [ ]:
#連線
server = 'sqyhi03az.database.windows.net'
username = 'irentadmin'
password = 'hims@QaWsEd'
database = 'IRENT_V2'
driver = '{ODBC Driver 17 for SQL Server}'
# connectionString = 'DRIVER={0};PORT=1433;SERVER={1};DATABASE={2};UID={3};PWD={4}'.format(driver, server, database, username, password)
connectionString = f'DRIVER={driver};PORT=1433;SERVER={server};DATABASE={database};UID={username};PWD={password}'
cnxn = pyodbc.connect(connectionString)
cursor = cnxn.cursor()

for i in range(len(lst_sql)):
    if lst_sql[i][0]!='':
        insertSql = f"insert into TB_Weather(DATE,WDSD,TEMP,HUMD,PRES,RAIN_24H,MAXTEMP,MINTEMP,WEATHER,CITY,LAT,LON,LOCATION)\
        values ('{lst_sql[i][0]}',{lst_sql[i][1]},{lst_sql[i][2]},{lst_sql[i][3]},{lst_sql[i][4]},{lst_sql[i][5]},{lst_sql[i][6]},\
        {lst_sql[i][7]},'{lst_sql[i][8]}','{lst_sql[i][9]}',{lst_sql[i][10]},{lst_sql[i][11]},'{lst_sql[i][12]}')"
        cursor.execute(insertSql) # 執行
    
cursor.commit()
cnxn.close()